const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let products=[],cart=JSON.parse(localStorage.getItem('ap_cart')||'[]'),me=null,adminUser=null;
const money=n=>Number(n)>0?'₹'+Number(n).toLocaleString('en-IN',{maximumFractionDigits:2}):'Contact for rate';
async function api(url,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};const r=await fetch(url,{credentials:'same-origin',...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function saveCart(){localStorage.setItem('ap_cart',JSON.stringify(cart));renderCart()}
async function loadProducts(){products=await api('/api/products');renderCategories();renderProducts()}
function renderCategories(){const cats=[...new Set(products.map(p=>p.category).filter(Boolean))].sort();const list=$('#categoryList');if(list)list.innerHTML=cats.map(c=>`<button onclick="filterCategory('${esc(c)}')">💊 ${esc(c)}</button>`).join('');const sel=$('#categoryFilter');if(sel)sel.innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}
function filterCategory(c){$('#categoryFilter').value=c;location.hash='products';renderProducts()}
function renderProducts(){const box=$('#productGrid');if(!box)return;const q=($('#search')?.value||'').toLowerCase().trim(),cat=$('#categoryFilter')?.value||'';const list=products.filter(p=>(!q||[p.name,p.salt,p.category,p.packing].join(' ').toLowerCase().includes(q))&&(!cat||p.category===cat));box.innerHTML=list.map(p=>`<article class="product-card">${p.image_url?`<img class="product-image" src="${esc(p.image_url)}" alt="${esc(p.name)}">`:'<div class="product-image placeholder">💊</div>'}<div class="product-tag">${esc(p.category||'Medicine')}</div><h3>${esc(p.name)}</h3><p>${esc(p.salt||'Composition available on request')}</p><small>${esc(p.packing||'')}</small><div class="price"><b>${money(p.wholesale_price)}</b><span>MRP ${money(p.mrp)}</span></div>${p.stock>0?`<small>Stock: ${p.stock}</small>`:'<small>Availability on request</small>'}<button onclick="addToCart(${p.id})">Add to order</button></article>`).join('')||'<p>No products found.</p>'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.find(x=>x.productId===id);x?x.qty++:cart.push({productId:id,qty:1});saveCart();show('cart')}
function renderCart(){const box=$('#cartItems');if(!box)return;box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.productId);return p?`<div class="cart-row"><span>${esc(p.name)}</span><input type="number" min="1" value="${i.qty}" onchange="setQty(${p.id},this.value)"><b>${money(p.wholesale_price*i.qty)}</b><button onclick="removeCart(${p.id})">×</button></div>`:''}).join('')||'<p>Your order cart is empty.</p>';const total=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.productId);return s+(p?p.wholesale_price*i.qty:0)},0);if($('#cartTotal'))$('#cartTotal').textContent=money(total);if($('#cartCount'))$('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function setQty(id,q){const x=cart.find(x=>x.productId===id);if(x)x.qty=Math.max(1,Number(q)||1);saveCart()} function removeCart(id){cart=cart.filter(x=>x.productId!==id);saveCart()}
function show(type){if(type==='cart')return openCart();if(type==='login')return openLogin();location.hash=type}
function openCart(){openModal(`<h2>Your Wholesale Order</h2><div id="cartItems"></div><div class="cart-total">Total: <b id="cartTotal">₹0</b></div><textarea id="orderNotes" rows="3" placeholder="Order notes / delivery instructions"></textarea><button class="btn green" onclick="placeOrder()">Place Order</button>`);renderCart()}
function openLogin(){openModal(`<div class="auth-grid"><div><h2>Retailer Login</h2><input id="loginUsername" placeholder="Mobile / Email / Username"><input id="loginPassword" type="password" placeholder="Password"><button class="btn green" onclick="login()">Login</button></div><div><h2>Create Retailer Account</h2><input id="regStore" placeholder="Medical Store Name *"><input id="regOwner" placeholder="Owner Name"><input id="regMobile" placeholder="Mobile *"><input id="regEmail" type="email" placeholder="Email"><input id="regPassword" type="password" placeholder="Password (min 8 chars) *"><input id="regGstin" placeholder="GSTIN (optional)"><input id="regLicense" placeholder="Drug Licence No. (optional)"><textarea id="regAddress" placeholder="Delivery Address"></textarea><button class="btn green" onclick="register()">Register</button></div></div>`)}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')} function closeModal(){$('#modal').classList.add('hidden')}
async function login(){try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:$('#loginUsername').value.trim(),password:$('#loginPassword').value})});me=d.user;closeModal();refreshAccount();alert('Login successful');}catch(e){alert(e.message)}}
async function register(){try{const body={storeName:$('#regStore').value.trim(),ownerName:$('#regOwner').value.trim(),mobile:$('#regMobile').value.trim(),email:$('#regEmail').value.trim(),password:$('#regPassword').value,gstin:$('#regGstin').value.trim(),drugLicense:$('#regLicense').value.trim(),address:$('#regAddress').value.trim()};const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify(body)});me=d.user;closeModal();refreshAccount();alert('Registration successful');}catch(e){alert(e.message)}}
async function placeOrder(){if(!cart.length)return alert('Cart is empty');if(!me)return openLogin();try{const d=await api('/api/orders',{method:'POST',body:JSON.stringify({items:cart,storeName:me.store_name||'',mobile:me.mobile||'',address:me.address||'',notes:$('#orderNotes')?.value||''})});cart=[];saveCart();closeModal();alert(`Order ${d.order_no} placed successfully`);await loadProducts()}catch(e){alert(e.message)}}
function refreshAccount(){if(!me)return;$('#accountButtonText').textContent=me.store_name||'Account';$('#accountTitle').textContent=`Welcome, ${me.store_name||'Retailer'}`;$('#accountText').textContent=`${me.mobile||''} • ${me.email||''}`;$('#accountActions').innerHTML='<button class="btn green" onclick="loadMyOrders()">My Orders</button> <button class="btn light" onclick="logout()">Logout</button>'}
async function logout(){await api('/api/auth/logout',{method:'POST'});me=null;adminUser=null;refreshAccount();location.reload()}
async function loadMe(){try{me=await api('/api/me');refreshAccount()}catch{me=null}}
async function loadMyOrders(){try{const rows=await api('/api/orders');openModal(`<h2>My Orders</h2>${rows.length?rows.map(o=>`<div class="order-card"><b>${esc(o.order_no)}</b><span>${esc(o.status)}</span><small>${esc(o.created_at)}</small><strong>${money(o.total)}</strong></div>`).join(''):'<p>No orders yet.</p>'}`)}catch(e){alert(e.message)}}
function clearSearch(){$('#search').value='';$('#categoryFilter').value='';renderProducts()}
async function showAdmin(e){if(e)e.preventDefault();if(!adminUser){openAdminLogin();return}$('#adminPanel').classList.remove('hidden');adminTab('dashboard');location.hash='adminPanel'}
function openAdminLogin(){openModal(`<h2>Admin Login</h2><p class="muted">Use the production admin credentials configured in your server environment.</p><input id="adminUsername" placeholder="Admin username"><input id="adminPassword" type="password" placeholder="Admin password"><button class="btn green" onclick="adminLogin()">Secure Login</button>`)}
async function adminLogin(){try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:$('#adminUsername').value.trim(),password:$('#adminPassword').value})});if(d.user.role!=='ADMIN')throw new Error('This account is not an admin account');adminUser=d.user;closeModal();$('#adminPanel').classList.remove('hidden');adminTab('dashboard');location.hash='adminPanel'}catch(e){alert(e.message)}}
async function adminLogout(){await api('/api/auth/logout',{method:'POST'});adminUser=null;$('#adminPanel').classList.add('hidden');alert('Admin logged out')}
async function adminTab(tab){if(!adminUser)return openAdminLogin();const c=$('#adminContent');c.innerHTML='<div class="loading">Loading…</div>';try{if(tab==='dashboard')return adminDashboard();if(tab==='products')return adminProducts();if(tab==='orders')return adminOrders();if(tab==='retailers')return adminRetailers()}catch(e){c.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function adminDashboard(){const d=await api('/api/admin/stats');$('#adminContent').innerHTML=`<h2>Dashboard</h2><div class="stats"><div><b>${d.products}</b><span>Active Products</span></div><div><b>${d.orders}</b><span>Total Orders</span></div><div><b>${d.retailers}</b><span>Retailers</span></div><div><b>${d.pending}</b><span>Pending Orders</span></div></div><div class="admin-note">Use <b>Products</b> to add medicines, upload photos, change MRP/wholesale price, stock, MOQ and schemes.</div>`}
async function adminProducts(){const ps=await api('/api/admin/products');$('#adminContent').innerHTML=`<div class="admin-head"><div><h2>Products</h2><p>Add and manage your medicine catalogue.</p></div><button class="btn green" onclick="productForm()">＋ Add Product</button></div><div class="table-wrap"><table><thead><tr><th>Photo</th><th>Product</th><th>Packing</th><th>MRP</th><th>Wholesale</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${p.image_url?`<img class="thumb" src="${esc(p.image_url)}">`:'💊'}</td><td><b>${esc(p.name)}</b><small>${esc(p.salt||'')}</small></td><td>${esc(p.packing||'')}</td><td>${money(p.mrp)}</td><td>${money(p.wholesale_price)}</td><td>${p.stock}</td><td><button onclick='productForm(${JSON.stringify(p)})'>Edit</button> <button class="danger" onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
async function adminOrders(){const os=await api('/api/orders');$('#adminContent').innerHTML=`<h2>Orders</h2><div class="table-wrap"><table><thead><tr><th>Order</th><th>Retailer</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>${os.map(o=>`<tr><td><b>${esc(o.order_no)}</b></td><td>${esc(o.store_name)}<small>${esc(o.mobile||'')}</small></td><td>${money(o.total)}</td><td><select onchange="changeOrderStatus(${o.id},this.value)">${['PENDING','CONFIRMED','DISPATCHED','DELIVERED','CANCELLED'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td>${esc(o.created_at)}</td></tr>`).join('')}</tbody></table></div>`}
async function adminRetailers(){const rs=await api('/api/admin/retailers');$('#adminContent').innerHTML=`<h2>Retailers</h2><div class="table-wrap"><table><thead><tr><th>Store</th><th>Owner</th><th>Mobile</th><th>GSTIN</th><th>Drug Licence</th><th>Joined</th></tr></thead><tbody>${rs.map(r=>`<tr><td><b>${esc(r.store_name)}</b><small>${esc(r.address||'')}</small></td><td>${esc(r.owner_name||'')}</td><td>${esc(r.mobile||'')}</td><td>${esc(r.gstin||'—')}</td><td>${esc(r.drug_license||'—')}</td><td>${esc(r.created_at)}</td></tr>`).join('')}</tbody></table></div>`}
function productForm(p={}){openModal(`<h2>${p.id?'Edit':'Add'} Product</h2><form id="productForm" onsubmit="saveProduct(event,${p.id||0})"><div class="form-grid"><label>Product name *<input name="name" required value="${esc(p.name||'')}"></label><label>Salt / composition<input name="salt" value="${esc(p.salt||'')}"></label><label>Category<input name="category" value="${esc(p.category||'')}"></label><label>Packing<input name="packing" value="${esc(p.packing||'')}"></label><label>MRP (₹)<input name="mrp" type="number" step="0.01" min="0" value="${p.mrp||0}"></label><label>Wholesale price (₹)<input name="wholesalePrice" type="number" step="0.01" min="0" value="${p.wholesale_price||0}"></label><label>MOQ<input name="moq" type="number" min="1" value="${p.moq||1}"></label><label>Stock<input name="stock" type="number" min="0" value="${p.stock||0}"></label><label>HSN<input name="hsn" value="${esc(p.hsn||'')}"></label><label>GST rate %<input name="gstRate" type="number" step="0.01" min="0" value="${p.gst_rate||0}"></label><label>Scheme<input name="scheme" value="${esc(p.scheme||'')}"></label><label>Product image<input id="productImage" name="image" type="file" accept="image/jpeg,image/png,image/webp"></label></div><div id="imagePreview">${p.image_url?`<img class="preview" src="${esc(p.image_url)}">`:''}</div><button class="btn green" type="submit">Save Product</button></form>`)}
async function saveProduct(e,id){e.preventDefault();const f=$('#productForm'),fd=new FormData(f);let imageUrl=f.dataset.image||'';const file=$('#productImage').files[0];try{if(file){const up=new FormData();up.append('image',file);const u=await fetch('/api/admin/uploads/image',{method:'POST',body:up,credentials:'same-origin'});const ud=await u.json();if(!u.ok)throw new Error(ud.error||'Image upload failed');imageUrl=ud.url}const body={name:fd.get('name'),salt:fd.get('salt'),category:fd.get('category'),packing:fd.get('packing'),mrp:fd.get('mrp'),wholesalePrice:fd.get('wholesalePrice'),scheme:fd.get('scheme'),moq:fd.get('moq'),stock:fd.get('stock'),hsn:fd.get('hsn'),gstRate:fd.get('gstRate'),imageUrl};await api(id?`/api/admin/products/${id}`:'/api/admin/products',{method:id?'PUT':'POST',body:JSON.stringify(body)});closeModal();await loadProducts();adminTab('products');alert('Product saved successfully')}catch(e){alert(e.message)}}
async function deleteProduct(id){if(!confirm('Delete this product from the public catalogue?'))return;try{await api(`/api/admin/products/${id}`,{method:'DELETE'});await loadProducts();adminTab('products')}catch(e){alert(e.message)}}
async function changeOrderStatus(id,status){try{await api(`/api/admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})})}catch(e){alert(e.message)}}
async function init(){await loadMe();await loadProducts();renderCart();}
window.addToCart=addToCart;window.setQty=setQty;window.removeCart=removeCart;window.login=login;window.register=register;window.placeOrder=placeOrder;window.show=show;window.openLogin=openLogin;window.closeModal=closeModal;window.filterCategory=filterCategory;window.clearSearch=clearSearch;window.showAdmin=showAdmin;window.adminTab=adminTab;window.adminLogin=adminLogin;window.adminLogout=adminLogout;window.productForm=productForm;window.saveProduct=saveProduct;window.deleteProduct=deleteProduct;window.changeOrderStatus=changeOrderStatus;window.loadMyOrders=loadMyOrders;
init();
